/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.gmt.emfacade.swt.validation;

import org.eclipse.emf.common.util.EList;
import org.eclipse.gmt.emfacade.swt.CapStyle;
import org.eclipse.gmt.emfacade.swt.JoinStyle;
import org.eclipse.gmt.emfacade.swt.LineStyle;

/**
 * A sample validator interface for {@link org.eclipse.gmt.emfacade.swt.LineAttributes}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LineAttributesValidator {
	boolean validate();

	boolean validateWidth(float value);
	boolean validateStyle(LineStyle value);
	boolean validateCap(CapStyle value);
	boolean validateJoin(JoinStyle value);
	boolean validateDash(EList<Float> value);
	boolean validateDashOffset(float value);
	boolean validateMiterLimit(float value);
}
