/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.gmt.emfacade.swt.validation;

import org.eclipse.emf.common.util.EList;
import org.eclipse.gmt.emfacade.swt.MultiplicityStyle;

/**
 * A sample validator interface for {@link org.eclipse.gmt.emfacade.swt.List}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ListValidator {
	boolean validate();

	boolean validateMultiplicityStyle(MultiplicityStyle value);

	boolean validateSelectionIndices(EList<Integer> value);

	boolean validateSelection(EList<String> value);

	boolean validateItems(EList<String> value);
}
