/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.gmt.emfacade.draw2d.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.gmt.emfacade.swt.CapStyle;
import org.eclipse.gmt.emfacade.swt.JoinStyle;
import org.eclipse.gmt.emfacade.swt.LineStyle;

/**
 * A sample validator interface for {@link org.eclipse.gmt.emfacade.draw2d.Shape}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ShapeValidator {
	boolean validate();

	boolean validateFill(boolean value);
	boolean validateFillXOR(boolean value);
	boolean validateOutline(boolean value);
	boolean validateOutlineXOR(boolean value);
	boolean validateAlpha(Integer value);
	boolean validateAntialias(Integer value);
	boolean validateLineWidthFloat(float value);
	boolean validateLineStyle(LineStyle value);
	boolean validateLineCap(CapStyle value);
	boolean validateLineJoin(JoinStyle value);
	boolean validateLineDash(EList<Float> value);
	boolean validateLineDashOffset(float value);
	boolean validateLineMiterLimit(float value);

	boolean validateLineMiterLimit(int value);
}
