/*
 * generated by Xtext
 */
package org.eclipse.gmt;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EmfacadeRuntimeModule extends org.eclipse.gmt.AbstractEmfacadeRuntimeModule {

	@Override
	public Class<? extends org.eclipse.xtext.naming.IQualifiedNameProvider> bindIQualifiedNameProvider() {
		return org.eclipse.gmt.scoping.EmfacadeQualifiedNameProvider.class;
	}

	public Class<? extends org.eclipse.xtext.scoping.IScopeProvider> bindIScopeProvider() {
		return org.eclipse.gmt.scoping.EmfacadeScopeProvider.class;
	}
	
	public Class<? extends org.eclipse.xtext.generator.IGenerator> bindIGenerator() {
		return org.eclipse.gmt.generator.EmfacadeGenerator.class;
	}
	
	public org.eclipse.xtext.xbase.XbaseFactory bindXbaseFactoryToInstance() {
		return org.eclipse.xtext.xbase.XbaseFactory.eINSTANCE;
	}

	public Class<? extends org.eclipse.xtext.xbase.scoping.featurecalls.OperatorMapping> bindOperatorMapping() {
		return org.eclipse.gmt.scoping.EmfacadeOperatorMapping.class;
	}
	
	public Class<? extends org.eclipse.xtext.xbase.scoping.featurecalls.StaticMethodsFeatureForTypeProvider.ExtensionClassNameProvider> bindExtensionClassNameProvider() {
		return org.eclipse.gmt.scoping.EmfacadeExtensionClassNameProvider.class;
	}
}
