/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.gmt.emfacade.draw2d.validation;

import org.eclipse.gmt.emfacade.draw2d.Figure;

/**
 * A sample validator interface for {@link org.eclipse.gmt.emfacade.draw2d.Draw2DCanvas}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface Draw2DCanvasValidator {
	boolean validate();

	boolean validateContents(Figure value);
}
