/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.gmt.emfacade.draw2d.validation;

import org.eclipse.draw2d.geometry.Dimension;
import org.eclipse.draw2d.geometry.Rectangle;

import org.eclipse.emf.common.util.EList;

import org.eclipse.gmt.emfacade.draw2d.Border;
import org.eclipse.gmt.emfacade.draw2d.Figure;

import org.eclipse.gmt.emfacade.swt.Color;
import org.eclipse.gmt.emfacade.swt.Font;

/**
 * A sample validator interface for {@link org.eclipse.gmt.emfacade.draw2d.Figure}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FigureValidator {
	boolean validate();

	boolean validateEnabled(boolean value);
	boolean validateVisible(boolean value);
	boolean validateOpaque(boolean value);
	boolean validateFocusTraversable(boolean value);
	boolean validateChildren(EList<Figure> value);
	boolean validateParent(Figure value);
	boolean validateBounds(Rectangle value);
	boolean validateMinimumSize(Dimension value);
	boolean validatePreferredSize(Dimension value);
	boolean validateMaximumSize(Dimension value);
	boolean validateToolTip(Figure value);
	boolean validateBackgroundColor(Color value);
	boolean validateForegroundColor(Color value);
	boolean validateFont(Font value);
	boolean validateBorder(Border value);
}
