/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.gmt.emfacade.draw2d.validation;

import org.eclipse.emf.common.util.URI;

import org.eclipse.gmt.emfacade.draw2d.Alignment;
import org.eclipse.gmt.emfacade.draw2d.Direction;

/**
 * A sample validator interface for {@link org.eclipse.gmt.emfacade.draw2d.Label}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LabelValidator {
	boolean validate();

	boolean validateText(String value);
	boolean validateTextAlignment(Alignment value);
	boolean validateTextPlacement(Direction value);
	boolean validateIcon(URI value);
	boolean validateIconAlignment(Alignment value);
	boolean validateIconTextGap(int value);
}
