/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.gmt.emfacade.swt.validation;


/**
 * A sample validator interface for {@link org.eclipse.gmt.emfacade.swt.Font}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FontValidator {
	boolean validate();

	boolean validateFontStyle(int value);
	boolean validateName(String value);
	boolean validateStyle(int value);

	boolean validateHeight(int value);

	boolean validateHeight(float value);
}
