/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.gmt.emfacade.swt.validation;


/**
 * A sample validator interface for {@link org.eclipse.gmt.emfacade.swt.RBGColor}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RBGColorValidator {
	boolean validate();

	boolean validateRed(int value);
	boolean validateGreen(int value);
	boolean validateBlue(int value);
}
