/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.gmt.emfacade.swt.validation;

import org.eclipse.emf.common.util.EList;
import org.eclipse.gmt.emfacade.swt.SortDirection;
import org.eclipse.gmt.emfacade.swt.TreeColumn;
import org.eclipse.gmt.emfacade.swt.TreeViewer;

/**
 * A sample validator interface for {@link org.eclipse.gmt.emfacade.swt.Tree}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TreeValidator {
	boolean validate();

	boolean validateColumns(EList<TreeColumn> value);

	boolean validateColumns(TreeColumn value);
	boolean validateHeaderVisible(boolean value);
	boolean validateLinesVisible(boolean value);
	boolean validateSortColumn(TreeColumn value);
	boolean validateSortDirection(SortDirection value);

	boolean validateViewer(TreeViewer value);
}
