/*
* generated by Xtext
*/
package org.eclipse.gmt.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.gmt.services.EmfacadeGrammarAccess;

public class EmfacadeParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private EmfacadeGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.eclipse.gmt.parser.antlr.internal.InternalEmfacadeParser createParser(XtextTokenStream stream) {
		return new org.eclipse.gmt.parser.antlr.internal.InternalEmfacadeParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "FacadeModel";
	}
	
	public EmfacadeGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(EmfacadeGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
