/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.gmt.emfacade.swt.validation;

import org.eclipse.emf.common.util.URI;

/**
 * A sample validator interface for {@link org.eclipse.gmt.emfacade.swt.Browser}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BrowserValidator {
	boolean validate();

	boolean validateJavascriptEnabled(boolean value);
	boolean validateText(String value);
	boolean validateUrl(URI value);
}
