/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.gmt.emfacade.swt.validation;

import org.eclipse.gmt.emfacade.swt.ArrowStyle;
import org.eclipse.gmt.emfacade.swt.ButtonStyle;

/**
 * A sample validator interface for {@link org.eclipse.gmt.emfacade.swt.Button}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ButtonValidator {
	boolean validate();

	boolean validateButtonStyle(ButtonStyle value);
	boolean validateArrowStyle(ArrowStyle value);

	boolean validateSelection(boolean value);
}
