/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.gmt.emfacade.swt.validation;

import org.eclipse.gmt.emfacade.swt.Control;
import org.eclipse.gmt.emfacade.swt.CoolBar;
import org.eclipse.swt.graphics.Point;

/**
 * A sample validator interface for {@link org.eclipse.gmt.emfacade.swt.CoolItem}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CoolItemValidator {
	boolean validate();

	boolean validateParent(CoolBar value);
	boolean validateControl(Control value);
	boolean validateMinimumSize(Point value);
	boolean validatePreferredSize(Point value);
	boolean validateSize(Point value);
}
