/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.gmt.emfacade.swt.validation;

import org.eclipse.emf.common.util.EList;
import org.eclipse.gmt.emfacade.swt.CoolItem;
import org.eclipse.gmt.emfacade.swt.OrientationStyle;

/**
 * A sample validator interface for {@link org.eclipse.gmt.emfacade.swt.CoolBar}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CoolBarValidator {
	boolean validate();

	boolean validateItems(EList<CoolItem> value);
	boolean validateOrientationStyle(OrientationStyle value);
}
