/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.gmt.emfacade.swt.validation;

import org.eclipse.gmt.emfacade.swt.Control;
import org.eclipse.gmt.emfacade.swt.FormAttachmentAlignment;

/**
 * A sample validator interface for {@link org.eclipse.gmt.emfacade.swt.FormAttachment}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FormAttachmentValidator {
	boolean validate();

	boolean validateAlignment(FormAttachmentAlignment value);
	boolean validateControl(Control value);
	boolean validateDenominator(int value);
	boolean validateNumerator(int value);
	boolean validateOffset(int value);
}
