/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.gmt.emfacade.swt.validation;

import org.eclipse.gmt.emfacade.swt.Button;
import org.eclipse.gmt.emfacade.swt.ModalStyle;
import org.eclipse.gmt.emfacade.swt.TrimStyle;

/**
 * A sample validator interface for {@link org.eclipse.gmt.emfacade.swt.Shell}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ShellValidator {
	boolean validate();

	boolean validateModalStyle(ModalStyle value);

	boolean validateModelStyle(ModalStyle value);
	boolean validateTrimStyle(TrimStyle value);
	boolean validateFullScreen(boolean value);
	boolean validateAlpha(int value);

	boolean validateDefaultButton(Button value);
}
