/*
 * generated by Xtext
 */
package org.eclipse.gmt.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EmfacadeUiModule extends org.eclipse.gmt.ui.AbstractEmfacadeUiModule {
	public EmfacadeUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
