/*
* generated by Xtext
*/
package org.eclipse.gmt.ui.contentassist;

import org.eclipse.gmt.ui.contentassist.AbstractEmfacadeProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class EmfacadeProposalProvider extends AbstractEmfacadeProposalProvider {

}
